alias gcm='git checkout main'
alias gcmtr='git checkout master'
alias gtfo='git push --set-upstream origin $(git branch --show-current)'
alias gclean='git clean -df'
alias grbias='git fetch origin && git rebase  --interactive --autosquash origin/main'
alias gpfwl='git push --force-with-lease'
alias greset='git reset --hard origin/$(git branch --show-current)'
